'use client';

import { useEffect } from "react";
import { usePathname } from "next/navigation";
import Head from "next/head";

const Metadata = () => {
  const pathname = usePathname();
  const isPlatformRoute = pathname && pathname.includes('/platform');
  const brandName = process.env.NEXT_PUBLIC_BRAND_NAME; 

  useEffect(() => {
    if (isPlatformRoute) {
      document.title = `${brandName} | Plataforma`;
    } else {
      document.title = brandName;
    }
  }, [isPlatformRoute, brandName]);

  return (
    <Head>
      <meta name="description" content="Generated by create next app" />
    </Head>
  );
};

export default Metadata;
