-- Drop tables if they exist
DROP TABLE IF EXISTS public.currency_types CASCADE;
DROP TABLE IF EXISTS public.platform_user_businesses CASCADE;
DROP TABLE IF EXISTS public.platform_plugins CASCADE;
DROP TABLE IF EXISTS public.stock_products;
DROP TABLE IF EXISTS public.sale_items CASCADE;
DROP TABLE IF EXISTS public.sales CASCADE;
DROP TABLE IF EXISTS public.stock_product_categories CASCADE;
DROP TABLE IF EXISTS public.stock_product_measure_units CASCADE;
DROP TABLE IF EXISTS public.payment_methods CASCADE;
DROP TABLE IF EXISTS public.countries CASCADE;
DROP TABLE IF EXISTS public.platform_user_genders CASCADE;
DROP TABLE IF EXISTS public.platform_users CASCADE;
DROP TABLE IF EXISTS public.platform_user_roles CASCADE;
DROP TABLE IF EXISTS public.platform_states CASCADE;
DROP TABLE IF EXISTS public.platform_settings CASCADE;

-- Create tables
create table public.stock_product_categories (
  id bigint generated by default as identity not null,
  name character varying(100) not null,
  description text null,
  platform_user_business_id bigint null,
  constraint stock_product_categories_pkey primary key (id),
  constraint stock_product_categories_name_key unique (name),
  constraint stock_product_categories_platform_user_business_id_fkey foreign KEY (platform_user_business_id) references platform_user_businesses (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.stock_product_measure_units (
  id bigint generated by default as identity not null,
  name character varying(100) not null,
  description text null,
  platform_user_business_id bigint null,
  constraint stock_product_measure_units_pkey primary key (id),
  constraint stock_product_measure_units_name_key unique (name),
  constraint stock_product_measure_units_platform_user_business_id_fkey foreign KEY (platform_user_business_id) references platform_user_businesses (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.stock_products (
  id bigint generated by default as identity not null,
  name character varying(100) not null,
  description text null,
  has_image boolean not null default false,
  image_path text null,
  stock_product_category_id integer not null,
  price numeric(10, 2) not null,
  stock_product_measure_unit_id integer not null,
  quantity integer not null,
  has_bar_code boolean not null default false,
  bar_code text null,
  created_at timestamp without time zone null default CURRENT_TIMESTAMP,
  platform_user_business_id bigint null,
  constraint stock_products_pkey primary key (id),
  constraint stock_products_platform_user_business_id_fkey foreign KEY (platform_user_business_id) references platform_user_businesses (id) on update CASCADE on delete CASCADE,
  constraint stock_products_stock_product_category_id_fkey foreign KEY (stock_product_category_id) references stock_product_categories (id),
  constraint stock_products_stock_product_measure_unit_id_fkey foreign KEY (stock_product_measure_unit_id) references stock_product_measure_units (id)
) TABLESPACE pg_default;

CREATE TABLE public.currency_types (
    id SERIAL PRIMARY KEY,
    abbreviation VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    UNIQUE (abbreviation),
    created_at TIMESTAMP with time zone NOT NULL default now()
);

CREATE TABLE public.payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NULL,
    created_at TIMESTAMP with time zone NOT NULL default now(),
    CONSTRAINT payment_methods_pkey PRIMARY KEY (id)
  ) TABLESPACE pg_default;

CREATE TABLE public.countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    abbreviation VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UNIQUE (abbreviation),
    CONSTRAINT countries_pkey PRIMARY KEY (id)
);

create table public.platform_user_businesses (
  id bigint generated by default as identity not null,
  name text null,
  enabled_plugins jsonb not null default '[]'::jsonb,
  constraint platform_user_businesses_pkey primary key (id)
) TABLESPACE pg_default;

create table public.platform_plugins (
  id bigint generated by default as identity not null,
  name text not null,
  description text null
) TABLESPACE pg_default;

CREATE TABLE public.platform_user_genders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    abbreviation VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UNIQUE (abbreviation),
    CONSTRAINT platform_user_genders_pkey PRIMARY KEY (id)
);

CREATE TABLE public.platform_settings (
    id BIGINT generated by default AS identity,
    contact_number VARCHAR(15) NULL,
    developer_name VARCHAR(100) NOT NULL,
    developer_contact_email VARCHAR(100) NULL,
    created_at TIMESTAMP with time zone NOT NULL default now(),
    CONSTRAINT platform_settings_pkey PRIMARY KEY (id),
    CONSTRAINT platform_settings_name_key UNIQUE (developer_name)
) TABLESPACE pg_default;

CREATE TABLE public.platform_user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NULL,
    CONSTRAINT platform_user_role_pkey PRIMARY KEY (id)
);

CREATE TABLE public.platform_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT,
    last_name TEXT,
    phone TEXT,
    email TEXT UNIQUE,
    username TEXT,
    password TEXT,
    is_root BOOLEAN DEFAULT FALSE,
    user_role_id BIGINT,
    is_active BOOLEAN DEFAULT FALSE,
    is_banned BOOLEAN DEFAULT FALSE,
    is_blocked BOOLEAN DEFAULT FALSE,
    token TEXT,
    dni_ssn TEXT,
    platform_user_gender_id BIGINT DEFAULT 4,
    country_id BIGINT,
    birthdate DATE,
    platform_user_business_id BIGINT NULL DEFAULT 1,
    created_by_user_id BIGINT NULL,
    CONSTRAINT platform_users_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) 
        REFERENCES platform_users (id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT platform_users_country_id_fkey FOREIGN KEY (country_id) 
        REFERENCES countries (id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT platform_users_platform_user_business_id_fkey FOREIGN KEY (platform_user_business_id) 
        REFERENCES platform_user_businesses (id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT platform_users_platform_user_gender_id_fkey FOREIGN KEY (platform_user_gender_id) 
        REFERENCES platform_user_genders (id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT platform_users_user_role_id_fkey FOREIGN KEY (user_role_id) 
        REFERENCES platform_user_roles (id) ON UPDATE CASCADE ON DELETE SET NULL
) TABLESPACE pg_default;

CREATE TABLE public.platform_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT platform_states_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

create table public.sales (
  id bigint generated by default as identity not null,
  platform_user_id bigint not null,
  sale_date timestamp with time zone not null default now(),
  sale_total numeric(10, 2) not null,
  is_closed boolean null default false,
  created_at timestamp with time zone not null default now(),
  platform_user_business_id bigint not null,
  constraint sales_pkey primary key (id),
  constraint sales_platform_user_business_id_fkey foreign KEY (platform_user_business_id) references platform_user_businesses (id) on update CASCADE on delete CASCADE,
  constraint sales_platform_user_id_fkey foreign KEY (platform_user_id) references platform_users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

CREATE TABLE public.sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL,
    stock_product_id BIGINT NOT NULL,
    quantity INT DEFAULT 1,
    sale_item_total DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_sale_item_product FOREIGN KEY (stock_product_id) 
        REFERENCES stock_products(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_sale_item_sale FOREIGN KEY (sale_id) 
        REFERENCES sales(id) ON DELETE CASCADE ON UPDATE CASCADE
) TABLESPACE pg_default;

